using EaaS.Api.Middleware;
using FluentAssertions;
using Microsoft.AspNetCore.Http;
using Xunit;

namespace EaaS.Api.Tests.Middleware;

public sealed class CorrelationIdMiddlewareTests
{
    private static DefaultHttpContext CreateHttpContext()
    {
        var context = new DefaultHttpContext();
        context.Response.Body = new MemoryStream();
        return context;
    }

    [Fact]
    public async Task Should_GenerateCorrelationId_When_HeaderIsMissing()
    {
        var httpContext = CreateHttpContext();
        var middleware = new CorrelationIdMiddleware(_ => Task.CompletedTask);

        await middleware.InvokeAsync(httpContext);

        httpContext.Items["CorrelationId"].Should().NotBeNull();
        httpContext.Items["CorrelationId"].Should().BeOfType<string>();
        ((string)httpContext.Items["CorrelationId"]!).Should().NotBeNullOrWhiteSpace();
    }

    [Fact]
    public async Task Should_UseProvidedCorrelationId_When_HeaderIsPresent()
    {
        var httpContext = CreateHttpContext();
        var expectedId = "abc123def456789012345678901234ab";
        httpContext.Request.Headers["X-Correlation-Id"] = expectedId;
        var middleware = new CorrelationIdMiddleware(_ => Task.CompletedTask);

        await middleware.InvokeAsync(httpContext);

        httpContext.Items["CorrelationId"].Should().Be(expectedId);
    }

    [Fact]
    public async Task Should_SetResponseHeader_With_CorrelationId()
    {
        var httpContext = CreateHttpContext();
        var middleware = new CorrelationIdMiddleware(_ => Task.CompletedTask);

        await middleware.InvokeAsync(httpContext);

        httpContext.Response.Headers["X-Correlation-Id"].ToString().Should().NotBeNullOrWhiteSpace();
    }

    [Fact]
    public async Task Should_SetResponseHeader_Matching_RequestHeader_When_Provided()
    {
        var httpContext = CreateHttpContext();
        var expectedId = "abc123def456789012345678901234ab";
        httpContext.Request.Headers["X-Correlation-Id"] = expectedId;
        var middleware = new CorrelationIdMiddleware(_ => Task.CompletedTask);

        await middleware.InvokeAsync(httpContext);

        httpContext.Response.Headers["X-Correlation-Id"].ToString().Should().Be(expectedId);
    }

    [Fact]
    public async Task Should_GenerateCorrelationId_As32CharString_When_AutoGenerated()
    {
        var httpContext = CreateHttpContext();
        var middleware = new CorrelationIdMiddleware(_ => Task.CompletedTask);

        await middleware.InvokeAsync(httpContext);

        var correlationId = (string)httpContext.Items["CorrelationId"]!;
        correlationId.Should().HaveLength(32);
    }
}
