// <auto-generated />
using System;
using EaaS.Domain.Enums;
using EaaS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EaaS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414185323_AddWebhookDeliveriesDedup")]
    partial class AddWebhookDeliveriesDedup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "admin_role", new[] { "super_admin", "admin", "read_only" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "api_key_status", new[] { "active", "revoked", "rotating" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "audit_action", new[] { "tenant_created", "tenant_updated", "tenant_suspended", "tenant_activated", "tenant_deactivated", "admin_user_created", "admin_user_updated", "admin_user_deleted", "admin_login", "admin_login_failed", "settings_updated" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "dns_record_purpose", new[] { "spf", "dkim", "dmarc" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "dns_record_type", new[] { "txt", "cname", "mx" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "domain_status", new[] { "pending_verification", "verified", "failed", "suspended" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "email_status", new[] { "queued", "sending", "sent", "delivered", "bounced", "complained", "failed", "scheduled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "event_type", new[] { "queued", "scheduled", "sent", "delivered", "bounced", "complained", "opened", "clicked", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "inbound_email_status", new[] { "received", "processing", "processed", "forwarded", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "inbound_rule_action", new[] { "webhook", "forward", "store" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "invoice_status", new[] { "pending", "paid", "failed", "refunded" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_provider", new[] { "none", "stripe", "pay_stack", "flutterwave", "pay_pal" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "plan_tier", new[] { "free", "starter", "pro", "business", "enterprise" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "subscription_status", new[] { "trial", "active", "past_due", "cancelled", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "suppression_reason", new[] { "hard_bounce", "soft_bounce_limit", "complaint", "manual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tenant_status", new[] { "active", "suspended", "deactivated" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "webhook_status", new[] { "active", "inactive", "disabled" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EaaS.Domain.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<AdminRole>("Role")
                        .HasColumnType("admin_role")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_admin_users_email");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("EaaS.Domain.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.PrimitiveCollection<string[]>("AllowedDomains")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_domains")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsServiceKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_service_key");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("prefix");

                    b.Property<Guid?>("ReplacedByKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_key_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTime?>("RotatingExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotating_expires_at");

                    b.Property<ApiKeyStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("api_key_status")
                        .HasDefaultValue(ApiKeyStatus.Active)
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("uq_api_keys_key_hash");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_api_keys_tenant");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("idx_api_keys_status")
                        .HasFilter("status = 'active'");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("EaaS.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<AuditAction>("Action")
                        .HasColumnType("audit_action")
                        .HasColumnName("action");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Details")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("details")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("TargetId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("idx_audit_logs_action");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("idx_audit_logs_admin_user");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_audit_logs_created_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("EaaS.Domain.Entities.DnsRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActualValue")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("actual_value");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<DnsRecordPurpose>("Purpose")
                        .HasColumnType("dns_record_purpose")
                        .HasColumnName("purpose");

                    b.Property<string>("RecordName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("record_name");

                    b.Property<DnsRecordType>("RecordType")
                        .HasColumnType("dns_record_type")
                        .HasColumnName("record_type");

                    b.Property<string>("RecordValue")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("record_value");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.HasIndex("DomainId")
                        .HasDatabaseName("idx_dns_records_domain");

                    b.ToTable("dns_records", (string)null);
                });

            modelBuilder.Entity("EaaS.Domain.Entities.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_key_id");

                    b.Property<string>("Attachments")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("attachments")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("BatchId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("batch_id");

                    b.Property<string>("BccEmails")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("bcc_emails")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("CcEmails")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("cc_emails")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateTime?>("ClickedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("clicked_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FromEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("from_email");

                    b.Property<string>("FromName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("from_name");

                    b.Property<string>("HtmlBody")
                        .HasColumnType("text")
                        .HasColumnName("html_body");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("message_id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_message_id");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("SesMessageId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ses_message_id");

                    b.Property<EmailStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("email_status")
                        .HasDefaultValue(EmailStatus.Queued)
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)")
                        .HasColumnName("subject");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("tags")
                        .HasDefaultValueSql("'{}'");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TextBody")
                        .HasColumnType("text")
                        .HasColumnName("text_body");

                    b.Property<string>("ToEmails")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("to_emails");

                    b.Property<bool>("TrackClicks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("track_clicks");

                    b.Property<bool>("TrackOpens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("track_opens");

                    b.Property<string>("TrackingId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tracking_id");

                    b.Property<string>("Variables")
                        .HasColumnType("jsonb")
                        .HasColumnName("variables");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId")
                        .HasDatabaseName("idx_emails_api_key");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("idx_emails_batch")
                        .HasFilter("batch_id IS NOT NULL");

                    b.HasIndex("FromEmail")
                        .HasDatabaseName("idx_emails_from");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("idx_emails_message_id");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("idx_emails_template")
                        .HasFilter("template_id IS NOT NULL");

                    b.HasIndex("Status", "ScheduledAt")
                        .HasDatabaseName("ix_emails_scheduled")
                        .HasFilter("status = 'scheduled'");

                    b.HasIndex("TenantId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_emails_tenant_created");

                    b.HasIndex("TenantId", "Status", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("idx_emails_tenant_status");

                    b.ToTable("emails", (string)null);
                });

            modelBuilder.Entity("EaaS.Domain.Entities.EmailEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Data")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("data")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid>("EmailId")
                        .HasColumnType("uuid")
                        .HasColumnName("email_id");

                    b.Property<EventType>("EventType")
                        .HasColumnType("event_type")
                        .HasColumnName("event_type");

                    b.HasKey("Id");

                    b.HasIndex("EmailId")
                        .HasDatabaseName("idx_email_events_email");

                    b.HasIndex("EventType", "CreatedAt")
                        .HasDatabaseName("idx_email_events_type");

                    b.ToTable("email_events", (string)null);
                });

            modelBuilder.Entity("EaaS.Domain.Entities.InboundAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("filename");

                    b.Property<Guid>("InboundEmailId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbound_email_id");

                    b.Property<bool>("IsInline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_inline");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("s3_key");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("Id");

                    b.HasIndex("InboundEmailId")
                        .HasDatabaseName("idx_inbound_attachments_email");

                    b.ToTable("inbound_attachments", (string)null);
                });

            modelBuilder.Entity("EaaS.Domain.Entities.InboundEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BccEmails")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("bcc_emails")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("CcEmails")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("cc_emails")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DkimVerdict")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dkim_verdict");

                    b.Property<string>("DmarcVerdict")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dmarc_verdict");

                    b.Property<string>("FromEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("from_email");

                    b.Property<string>("FromName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("from_name");

                    b.Property<string>("Headers")
                        .HasColumnType("jsonb")
                        .HasColumnName("headers");

                    b.Property<string>("HtmlBody")
                        .HasColumnType("text")
                        .HasColumnName("html_body");

                    b.Property<string>("InReplyTo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("in_reply_to");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("message_id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid?>("OutboundEmailId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbound_email_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("References")
                        .HasColumnType("text")
                        .HasColumnName("references");

                    b.Property<string>("ReplyTo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reply_to");

                    b.Property<string>("S3Key")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("s3_key");

                    b.Property<decimal?>("SpamScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("spam_score");

                    b.Property<string>("SpamVerdict")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("spam_verdict");

                    b.Property<string>("SpfVerdict")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("spf_verdict");

                    b.Property<InboundEmailStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("inbound_email_status")
                        .HasDefaultValue(InboundEmailStatus.Received)
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("subject");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("tags")
                        .HasDefaultValueSql("'{}'");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TextBody")
                        .HasColumnType("text")
                        .HasColumnName("text_body");

                    b.Property<string>("ToEmails")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("to_emails");

                    b.Property<string>("VirusVerdict")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("virus_verdict");

                    b.HasKey("Id");

                    b.HasIndex("InReplyTo")
                        .HasDatabaseName("idx_inbound_emails_in_reply_to")
                        .HasFilter("in_reply_to IS NOT NULL");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("idx_inbound_emails_message_id");

                    b.HasIndex("OutboundEmailId")
                        .HasDatabaseName("idx_inbound_emails_outbound")
                        .HasFilter("outbound_email_id IS NOT NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_inbound_emails_tenant");

                    b.HasIndex("TenantId", "FromEmail")
                        .HasDatabaseName("idx_inbound_emails_from");

                    b.HasIndex("TenantId", "ReceivedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_inbound_emails_tenant_received");

                    b.ToTable("inbound_emails", (string)null);
                });

            modelBuilder.Entity("EaaS.Domain.Entities.InboundRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<InboundRuleAction>("Action")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("inbound_rule_action")
                        .HasDefaultValue(InboundRuleAction.Store)
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("DomainId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_id");

                    b.Property<string>("ForwardTo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("forward_to");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("MatchPattern")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("match_pattern");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("webhook_url");

                    b.HasKey("Id");

                    b.HasIndex("DomainId")
                        .HasDatabaseName("idx_inbound_rules_domain");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_inbound_rules_tenant");

                    b.ToTable("inbound_rules", (string)null);
                });

            modelBuilder.Entity("EaaS.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("AmountUsd")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount_usd");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("USD")
                        .HasColumnName("currency");

                    b.Property<string>("ExternalInvoiceId")
                        .HasColumnType("text")
                        .HasColumnName("external_invoice_id");

                    b.Property<string>("ExternalPaymentId")
                        .HasColumnType("text")
                        .HasColumnName("external_payment_id");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_number");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<PaymentProvider>("Provider")
                        .HasColumnType("payment_provider")
                        .HasColumnName("provider");

                    b.Property<InvoiceStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("invoice_status")
                        .HasDefaultValue(InvoiceStatus.Pending)
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_invoices_invoice_number");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_invoices_tenant_created");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("EaaS.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("AnnualPriceUsd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("annual_price_usd");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("CustomDomainBranding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("custom_domain_branding");

                    b.Property<int>("DailyEmailLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("daily_email_limit");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MaxApiKeys")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("max_api_keys");

                    b.Property<int>("MaxDomains")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("max_domains");

                    b.Property<int>("MaxTemplates")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("max_templates");

                    b.Property<int>("MaxWebhooks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("max_webhooks");

                    b.Property<long>("MonthlyEmailLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(3000L)
                        .HasColumnName("monthly_email_limit");

                    b.Property<decimal>("MonthlyPriceUsd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("monthly_price_usd");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<bool>("PrioritySupport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("priority_support");

                    b.Property<PlanTier>("Tier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("plan_tier")
                        .HasDefaultValue(PlanTier.Free)
                        .HasColumnName("tier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_plans_name");

                    b.HasIndex("Tier", "IsActive")
                        .HasDatabaseName("idx_plans_tier_active");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("EaaS.Domain.Entities.SendingDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("domain_name");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked_at");

                    b.Property<string>("SesIdentityArn")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ses_identity_arn");

                    b.Property<DomainStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("domain_status")
                        .HasDefaultValue(DomainStatus.PendingVerification)
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_domains_tenant");

                    b.HasIndex("TenantId", "DomainName")
                        .IsUnique()
                        .HasDatabaseName("uq_domains_tenant_name");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("idx_domains_status");

                    b.ToTable("domains", (string)null);
                });

            modelBuilder.Entity("EaaS.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<DateTime>("CurrentPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_start");

                    b.Property<string>("ExternalCustomerId")
                        .HasColumnType("text")
                        .HasColumnName("external_customer_id");

                    b.Property<string>("ExternalSubscriptionId")
                        .HasColumnType("text")
                        .HasColumnName("external_subscription_id");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<PaymentProvider>("Provider")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("payment_provider")
                        .HasDefaultValue(PaymentProvider.Stripe)
                        .HasColumnName("provider");

                    b.Property<SubscriptionStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("subscription_status")
                        .HasDefaultValue(SubscriptionStatus.Trial)
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_ends_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPeriodEnd")
                        .HasDatabaseName("idx_subscriptions_period_end");

                    b.HasIndex("PlanId");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("idx_subscriptions_tenant_status");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("EaaS.Domain.Entities.SuppressionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email_address");

                    b.Property<SuppressionReason>("Reason")
                        .HasColumnType("suppression_reason")
                        .HasColumnName("reason");

                    b.Property<string>("SourceMessageId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_message_id");

                    b.Property<DateTime>("SuppressedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suppressed_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .HasDatabaseName("idx_suppression_email");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_suppression_tenant");

                    b.HasIndex("TenantId", "EmailAddress")
                        .IsUnique()
                        .HasDatabaseName("uq_suppression_tenant_email");

                    b.ToTable("suppression_list", (string)null);
                });

            modelBuilder.Entity("EaaS.Domain.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_body");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SubjectTemplate")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("subject_template");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TextBody")
                        .HasColumnType("text")
                        .HasColumnName("text_body");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("VariablesSchema")
                        .HasColumnType("jsonb")
                        .HasColumnName("variables_schema");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_templates_tenant");

                    b.HasIndex("TenantId", "DeletedAt")
                        .HasDatabaseName("idx_templates_deleted")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_templates_tenant_name_active")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("EaaS.Domain.Entities.TemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("HtmlBody")
                        .HasColumnType("text")
                        .HasColumnName("html_body");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("TextBody")
                        .HasColumnType("text")
                        .HasColumnName("text_body");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_template_versions_template_created");

                    b.HasIndex("TemplateId", "Version")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_template_versions_template_version");

                    b.ToTable("template_versions", (string)null);
                });

            modelBuilder.Entity("EaaS.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_email");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("LegalEntityName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("legal_entity_name");

                    b.Property<int?>("MaxApiKeys")
                        .HasColumnType("integer")
                        .HasColumnName("max_api_keys");

                    b.Property<int?>("MaxDomainsCount")
                        .HasColumnType("integer")
                        .HasColumnName("max_domains_count");

                    b.Property<long?>("MonthlyEmailLimit")
                        .HasColumnType("bigint")
                        .HasColumnName("monthly_email_limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PostalAddress")
                        .HasColumnType("text")
                        .HasColumnName("postal_address");

                    b.Property<string>("PreferredEmailProviderKey")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("preferred_email_provider_key");

                    b.Property<TenantStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tenant_status")
                        .HasDefaultValue(TenantStatus.Active)
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Default",
                            Status = TenantStatus.Active,
                            UpdatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EaaS.Domain.Entities.TrackingLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ClickedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("clicked_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("EmailId")
                        .HasColumnType("uuid")
                        .HasColumnName("email_id");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("original_url");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("EmailId")
                        .HasDatabaseName("idx_tracking_links_email");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("idx_tracking_links_token");

                    b.ToTable("tracking_links", (string)null);
                });

            modelBuilder.Entity("EaaS.Domain.Entities.Webhook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ConsecutiveFailures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("consecutive_failures");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.PrimitiveCollection<string[]>("Events")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("events");

                    b.Property<string>("Secret")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("secret");

                    b.Property<WebhookStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("webhook_status")
                        .HasDefaultValue(WebhookStatus.Active)
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("idx_webhooks_tenant");

                    b.ToTable("webhooks", (string)null);
                });

            modelBuilder.Entity("EaaS.Domain.Entities.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("EmailId")
                        .HasColumnType("uuid")
                        .HasColumnName("email_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("FirstAttemptAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_attempt_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("ResponseBodySnippet")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("response_body_snippet");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("WebhookId")
                        .HasColumnType("uuid")
                        .HasColumnName("webhook_id");

                    b.HasKey("Id");

                    b.HasIndex("WebhookId", "EmailId", "EventType")
                        .IsUnique()
                        .HasDatabaseName("ux_webhook_deliveries_dedup");

                    b.ToTable("webhook_deliveries", (string)null);
                });

            modelBuilder.Entity("EaaS.Domain.Entities.WebhookDeliveryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("EmailId")
                        .HasColumnType("uuid")
                        .HasColumnName("email_id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<Guid>("WebhookId")
                        .HasColumnType("uuid")
                        .HasColumnName("webhook_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_webhook_delivery_logs_created");

                    b.HasIndex("EmailId")
                        .HasDatabaseName("idx_webhook_delivery_logs_email");

                    b.HasIndex("WebhookId")
                        .HasDatabaseName("idx_webhook_delivery_logs_webhook");

                    b.ToTable("webhook_delivery_logs", (string)null);
                });

            modelBuilder.Entity("EaaS.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("EaaS.Domain.Entities.Tenant", "Tenant")
                        .WithMany("ApiKeys")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("EaaS.Domain.Entities.AdminUser", "AdminUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.DnsRecord", b =>
                {
                    b.HasOne("EaaS.Domain.Entities.SendingDomain", "Domain")
                        .WithMany("DnsRecords")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.Email", b =>
                {
                    b.HasOne("EaaS.Domain.Entities.ApiKey", "ApiKey")
                        .WithMany("Emails")
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EaaS.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Emails")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApiKey");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.EmailEvent", b =>
                {
                    b.HasOne("EaaS.Domain.Entities.Email", "Email")
                        .WithMany("Events")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.InboundAttachment", b =>
                {
                    b.HasOne("EaaS.Domain.Entities.InboundEmail", "InboundEmail")
                        .WithMany("Attachments")
                        .HasForeignKey("InboundEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InboundEmail");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.InboundEmail", b =>
                {
                    b.HasOne("EaaS.Domain.Entities.Email", "OutboundEmail")
                        .WithMany()
                        .HasForeignKey("OutboundEmailId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EaaS.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutboundEmail");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.InboundRule", b =>
                {
                    b.HasOne("EaaS.Domain.Entities.SendingDomain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EaaS.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("EaaS.Domain.Entities.Subscription", "Subscription")
                        .WithMany("Invoices")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EaaS.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Invoices")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.SendingDomain", b =>
                {
                    b.HasOne("EaaS.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Domains")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("EaaS.Domain.Entities.Plan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EaaS.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.SuppressionEntry", b =>
                {
                    b.HasOne("EaaS.Domain.Entities.Tenant", "Tenant")
                        .WithMany("SuppressionEntries")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.Template", b =>
                {
                    b.HasOne("EaaS.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Templates")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.TemplateVersion", b =>
                {
                    b.HasOne("EaaS.Domain.Entities.Template", "Template")
                        .WithMany("Versions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.TrackingLink", b =>
                {
                    b.HasOne("EaaS.Domain.Entities.Email", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.Webhook", b =>
                {
                    b.HasOne("EaaS.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Webhooks")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.WebhookDelivery", b =>
                {
                    b.HasOne("EaaS.Domain.Entities.Webhook", "Webhook")
                        .WithMany()
                        .HasForeignKey("WebhookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Webhook");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.WebhookDeliveryLog", b =>
                {
                    b.HasOne("EaaS.Domain.Entities.Webhook", "Webhook")
                        .WithMany()
                        .HasForeignKey("WebhookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Webhook");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.AdminUser", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.ApiKey", b =>
                {
                    b.Navigation("Emails");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.Email", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.InboundEmail", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.Plan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.SendingDomain", b =>
                {
                    b.Navigation("DnsRecords");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.Template", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("EaaS.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Domains");

                    b.Navigation("Emails");

                    b.Navigation("Invoices");

                    b.Navigation("Subscriptions");

                    b.Navigation("SuppressionEntries");

                    b.Navigation("Templates");

                    b.Navigation("Webhooks");
                });
#pragma warning restore 612, 618
        }
    }
}
